# Generated by Django 2.2.5 on 2022-07-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='test',
            new_name='text',
        ),
    ]
